# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[profile.default]
solc = "0.8.17"
optimizer = true
optimizer_runs = 10_000
auto_detect_solc = false
verbosity = 3
libs = ["node_modules", "lib"]

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 1_000

[profile.via-ir]
via_ir = true

[profile.min-solc]
solc = "0.8.13"

[profile.min-solc-via-ir]
via_ir = true
solc = "0.8.13"

[profile.via-ir.fuzz]
runs = 10_000

[profile.min-solc.fuzz]
runs = 10_000

[profile.min-solc-via-ir.fuzz]
runs = 10_000

[profile.intense.fuzz]
runs = 10_000

[profile.intense.invariant]
runs = 5_000
