#
# Profiles: `default`, `bounded`, `unbounded`, `intense`, `min-solc`, `via-ir`, `min-solc-via-ir`
#
# ==================
# Profile: `default`
# ==================
[profile.default]
solc = "0.8.17"
optimizer = true
optimizer_runs = 10
auto_detect_solc = false
verbosity = 3
libs = ["node_modules", "lib"]

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 10
depth = 100
fail_on_revert = false

# ==================
# Profile: `bounded`
# ==================
[profile.bounded.invariant]
verbosity = 5
runs = 200
depth = 250
fail_on_revert = true

# ====================
# Profile: `unbounded`
# ====================
[profile.unbounded.invariant]
verbosity = 5
runs = 200
depth = 250
fail_on_revert = false

# ==================
# Profile: `intense`
# ==================
[profile.intense.fuzz]
runs = 10_000

[profile.intense.invariant]
runs = 10
depth = 100

# =================
# Profile: `via-ir`
# =================
[profile.via-ir]
via_ir = true

[profile.via-ir.fuzz]
runs = 1_000

[profile.via-ir.invariant]
runs = 10
depth = 100

# ===================
# Profile: `min-solc`
# ===================
[profile.min-solc]
solc = "0.8.13"

[profile.min-solc.fuzz]
runs = 1_000

[profile.min-solc.invariant]
runs = 10
depth = 100

# ==========================
# Profile: `min-solc-via-ir`
# ==========================
[profile.min-solc-via-ir]
via_ir = true
solc = "0.8.13"

[profile.min-solc-via-ir.fuzz]
runs = 1_000

[profile.min-solc-via-ir.invariant]
runs = 10
depth = 100
