name: lint

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - development
  pull_request:
    paths:
      - "lib/**"
      - "script/**"
      - "src/**"
      - "test/**"
      - "*.lock"
      - "Makefile"
      - "foundry.toml"
      - "remappings.txt"

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        node_version:
          - 19

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: |
          npm install

      - name: Run linter
        run: |
          make lint-check
